// Copyright (c) Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.
//
// Code generated by generator, DO NOT EDIT.

package model

// GetID returns ID of the resource.
func (i *Installation) GetID() string {
	return i.ID
}

// GetState returns State of the resource.
func (i *Installation) GetState() string {
	return string(i.State)
}

// IsDeleted determines whether the resource is deleted.
func (i *Installation) IsDeleted() bool {
	return i.DeleteAt > 0
}

// InstallationsAsResources returns collection as Resource objects.
func InstallationsAsResources(collection []*Installation) []Resource {
	resources := make([]Resource, 0, len(collection))
	for _, elem := range collection {
		resources = append(resources, Resource(elem))
	}
	return resources
}
