apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mattermost-operator
  template:
    metadata:
      labels:
        name: mattermost-operator
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - /mattermost-operator
        image: mattermost/mattermost-operator:v1.9.0
        imagePullPolicy: IfNotPresent
        name: mattermost-operator
      serviceAccountName: mattermost-operator
