# Docs: https://golangci-lint.run/usage/configuration/#config-file
version: "2"

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - predeclared
    - copyloopvar
    - staticcheck
    - unconvert
    - unused
  exclusions:
    paths:
      - internal/mocks
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    staticcheck:
      checks:
        - "all"
        - "-QF*"
        - "-ST*"

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
