version: 2
run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - internal/mocks

linters-settings:
  gofmt:
    simplify: true
  govet:
    enable-all: true
    disable:
      - fieldalignment

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - predeclared
    - copyloopvar
    - staticcheck
    - unconvert
    - unused
