serviceAccounts:
  alertmanager:
    create: false

server:
  persistentVolume:
    size: 100Gi
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-controller

alertmanager:
  enabled: false
