apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sloth
  namespace: prometheus
  labels:
    app: sloth
    prometheus: prometheus
spec:
  selector:
    matchLabels:
      app: sloth
  namespaceSelector:
    matchNames:
    - prometheus
  endpoints:
    - port: metrics
      interval: 60s
