// Code generated by MockGen. DO NOT EDIT.
// Source: ./model/installation_database.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/mattermost/mattermost-cloud/model"
	v1alpha1 "github.com/mattermost/mattermost-operator/pkg/apis/mattermost/v1alpha1"
	logrus "github.com/sirupsen/logrus"
	v1 "k8s.io/api/core/v1"
	reflect "reflect"
)

// MockDatabase is a mock of Database interface
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// Provision mocks base method
func (m *MockDatabase) Provision(store model.InstallationDatabaseStoreInterface, logger logrus.FieldLogger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provision", store, logger)
	ret0, _ := ret[0].(error)
	return ret0
}

// Provision indicates an expected call of Provision
func (mr *MockDatabaseMockRecorder) Provision(store, logger interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provision", reflect.TypeOf((*MockDatabase)(nil).Provision), store, logger)
}

// Teardown mocks base method
func (m *MockDatabase) Teardown(keepData bool, logger logrus.FieldLogger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Teardown", keepData, logger)
	ret0, _ := ret[0].(error)
	return ret0
}

// Teardown indicates an expected call of Teardown
func (mr *MockDatabaseMockRecorder) Teardown(keepData, logger interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Teardown", reflect.TypeOf((*MockDatabase)(nil).Teardown), keepData, logger)
}

// Snapshot mocks base method
func (m *MockDatabase) Snapshot(logger logrus.FieldLogger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", logger)
	ret0, _ := ret[0].(error)
	return ret0
}

// Snapshot indicates an expected call of Snapshot
func (mr *MockDatabaseMockRecorder) Snapshot(logger interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockDatabase)(nil).Snapshot), logger)
}

// GenerateDatabaseSpecAndSecret mocks base method
func (m *MockDatabase) GenerateDatabaseSpecAndSecret(logger logrus.FieldLogger) (*v1alpha1.Database, *v1.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDatabaseSpecAndSecret", logger)
	ret0, _ := ret[0].(*v1alpha1.Database)
	ret1, _ := ret[1].(*v1.Secret)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateDatabaseSpecAndSecret indicates an expected call of GenerateDatabaseSpecAndSecret
func (mr *MockDatabaseMockRecorder) GenerateDatabaseSpecAndSecret(logger interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDatabaseSpecAndSecret", reflect.TypeOf((*MockDatabase)(nil).GenerateDatabaseSpecAndSecret), logger)
}

// MockInstallationDatabaseStoreInterface is a mock of InstallationDatabaseStoreInterface interface
type MockInstallationDatabaseStoreInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInstallationDatabaseStoreInterfaceMockRecorder
}

// MockInstallationDatabaseStoreInterfaceMockRecorder is the mock recorder for MockInstallationDatabaseStoreInterface
type MockInstallationDatabaseStoreInterfaceMockRecorder struct {
	mock *MockInstallationDatabaseStoreInterface
}

// NewMockInstallationDatabaseStoreInterface creates a new mock instance
func NewMockInstallationDatabaseStoreInterface(ctrl *gomock.Controller) *MockInstallationDatabaseStoreInterface {
	mock := &MockInstallationDatabaseStoreInterface{ctrl: ctrl}
	mock.recorder = &MockInstallationDatabaseStoreInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInstallationDatabaseStoreInterface) EXPECT() *MockInstallationDatabaseStoreInterfaceMockRecorder {
	return m.recorder
}

// GetClusterInstallations mocks base method
func (m *MockInstallationDatabaseStoreInterface) GetClusterInstallations(filter *model.ClusterInstallationFilter) ([]*model.ClusterInstallation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterInstallations", filter)
	ret0, _ := ret[0].([]*model.ClusterInstallation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterInstallations indicates an expected call of GetClusterInstallations
func (mr *MockInstallationDatabaseStoreInterfaceMockRecorder) GetClusterInstallations(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterInstallations", reflect.TypeOf((*MockInstallationDatabaseStoreInterface)(nil).GetClusterInstallations), filter)
}
