apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost-cloud
  namespace: mattermost-cloud
  labels:
    app.kubernetes.io/name: mattermost-cloud
    app.kubernetes.io/component: provisioner
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: mattermost-cloud
      app.kubernetes.io/component: provisioner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mattermost-cloud
        app.kubernetes.io/component: provisioner
    spec:
      initContainers:
      - name: init-database
        image: mattermost/mattermost-cloud:latest
        imagePullPolicy: Always
        args: ["schema", "migrate", "--database", "$(DATABASE)"]
        env:
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: mattermost-cloud-secret
              key: DATABASE
      - name: volume-mount-hack
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "chown -R 10001:10001 /mattermost-cloud/clusters && rm -rf /mattermost-cloud/clusters/*"]
        volumeMounts:
        - name: cluster-persistent-storage
          mountPath: /mattermost-cloud/clusters/
      containers:
      - name: mattermost-cloud
        image: mattermost/mattermost-cloud:latest
        imagePullPolicy: Always
        terminationMessagePolicy: "FallbackToLogsOnError"
        args: ["server", "--debug", "true", "--state-store", "mattermost-kops-state-test", "--route53-id", "$(ROUTE53_ID)","--certificate-aws-arn", "$(CERTIFICATE_AWS_ARN)", "--private-route53-id", "$(PRIVATE_ROUTE53_ID)", "--private-dns", "$(PRIVATE_DNS)", "--private-subnets", "$(PRIVATE_SUBNETS)", "--public-subnets", "$(PUBLIC_SUBNETS)", "--database", "$(DATABASE)"]
        ports:
        - containerPort: 8075
          name: api
        resources:
          {}
        env:
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mattermost-cloud-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mattermost-cloud-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: mattermost-cloud-secret
              key: AWS_REGION
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: mattermost-cloud-secret
              key: AWS_REGION
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: mattermost-cloud-secret
              key: DATABASE
        - name: ROUTE53_ID
          valueFrom:
            secretKeyRef:
              name: mattermost-cloud-secret
              key: ROUTE53_ID
        - name: PRIVATE_ROUTE53_ID
          valueFrom:
            secretKeyRef:
              name: mattermost-cloud-secret
              key: PRIVATE_ROUTE53_ID
        - name: PRIVATE_DNS
          valueFrom:
            secretKeyRef:
              name: mattermost-cloud-secret
              key: PRIVATE_DNS
        - name: PRIVATE_SUBNETS
          valueFrom:
            secretKeyRef:
              name: mattermost-cloud-secret
              key: PRIVATE_SUBNETS
        - name: PUBLIC_SUBNETS
          valueFrom:
            secretKeyRef:
              name: mattermost-cloud-secret
              key: PUBLIC_SUBNETS
        - name: CERTIFICATE_AWS_ARN
          valueFrom:
            secretKeyRef:
              name: mattermost-cloud-secret
              key: CERTIFICATE_AWS_ARN
        volumeMounts:
        - name: cluster-persistent-storage
          mountPath: /mattermost-cloud/clusters/
        - name: mattermost-cloud-ssh-volume
          mountPath: /.ssh
        - name: mattermost-cloud-tmp-volume
          mountPath: /tmp
        - name: mattermost-cloud-helm-volume
          mountPath: /.helm
      volumes:
      - name: cluster-persistent-storage
        persistentVolumeClaim:
          claimName: cluster-pv-claim
      - name: mattermost-cloud-ssh-volume
        secret:
          secretName: mattermost-cloud-ssh-secret
      - name: mattermost-cloud-tmp-volume
        emptyDir: {}
      - name: mattermost-cloud-helm-volume
        emptyDir: {}
