name: docker-build
description: Reusable action to build repos' docker images

runs:
  using: composite
  steps:
    - name: ci/prepare-docker-environment
      uses: ./.github/actions/docker-prepare

    - name: cd/build-docker-e2e-pr
      run: make build-image-e2e-pr
      shell: bash
      if: github.event_name == 'pull_request'

    - name: cd/build-docker-e2e
      run: make build-image-e2e
      shell: bash
      if: github.event_name != 'pull_request'

    - name: cd/push-image-pr
      run: "make push-image-pr"
      shell: bash
      if: github.event_name == 'pull_request'

    - name: cd/push-image
      run: "make push-image"
      shell: bash
      if: github.event_name != 'pull_request'
