name: docker-build
description: Reusable action to build repos' docker images

runs:
  using: composite
  steps:
    - name: ci/prepare-docker-environment
      uses: ./.github/actions/docker-prepare
    - name: cd/scan-docker-security
      uses: aquasecurity/trivy-action@9ab158e8597f3b310480b9a69402b419bc03dbd5 # v0.8.0
      with:
        image-ref: "mattermost/mattermost-cloud"
        format: "table"
        ignore-unfixed: true
        vuln-type: "os,library"
        severity: "CRITICAL"

    - name: cd/build-docker-e2e-pr
      run: make build-image-e2e-pr
      shell: bash
      if: github.event_name == 'pull_request'

    - name: cd/build-docker-e2e
      run: make build-image-e2e
      shell: bash
      if: github.event_name != 'pull_request'

    - name: cd/scan-docker-security-e2e
      uses: aquasecurity/trivy-action@9ab158e8597f3b310480b9a69402b419bc03dbd5 # v0.8.0
      with:
        image-ref: "mattermost/mattermost-cloud-e2e"
        format: "table"
        ignore-unfixed: true
        vuln-type: "os,library"
        severity: "CRITICAL"

    - name: cd/push-image-pr
      run: "make push-image-pr"
      shell: bash
      if: github.event_name == 'pull_request'
    - name: cd/push-image
      run: "make push-image"
      shell: bash
      if: github.event_name != 'pull_request'
