apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mattermost-operator
  template:
    metadata:
      labels:
        name: mattermost-operator
    spec:
      serviceAccountName: mattermost-operator
      containers:
        - name: mattermost-operator
          image: mattermost/mattermost-operator:v1.1.1
          imagePullPolicy: IfNotPresent
          command:
          - mattermost-operator
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mattermost-operator"
