name: cd
on:
  workflow_run:
    workflows: [ "ci" ]
    types:
      - completed
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.2.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - name: cd/build-docker
        run: make build-image build-image-e2e

      - name: cd/docker-push
        run: TAG=${GITHUB_REF_NAME} ./scripts/push-docker.sh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          REF_NAME: ${{ github.ref_name }}
