name: cd
on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.2.0
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: cd/build-docker
        run: make build-image build-image-e2e

      - name: Set TAG variable
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/heads/ ]]; then
            # If the GITHUB_REF variable starts with "refs/heads/", set the TAG to the branch name
            export TAG=${GITHUB_REF#refs/heads/}
          else
            # Otherwise, set the TAG to the tag name
            export TAG=${GITHUB_REF#refs/tags/}
          fi

          # Display the value of the TAG variable for debugging purposes
          echo "TAG=$TAG"

      - name: cd/docker-push
        run: TAG=${TAG} ./scripts/push-docker.sh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          REF_NAME: ${{ github.ref_name }}
