name: cd

on:
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v3.2.0
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: cd/build-docker
        run: make build-image build-image-e2e

      - name: Set TAG variable
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/heads/ ]]; then
            # If the GITHUB_REF variable starts with "refs/heads/", set the TAG to the branch name
            export TAG=${GITHUB_REF#refs/heads/}
          else
            # Otherwise, set the TAG to the tag name
            export TAG=${GITHUB_REF#refs/tags/}
          fi

          # Display the value of the TAG variable for debugging purposes
          echo "TAG=$TAG"

      - name: cd/docker-push
        run: TAG=${TAG} ./scripts/push-docker.sh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          REF_NAME: ${{ github.ref_name }}
